// Copyright 2025 Buf Technologies, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package hyperpb

import (
	"errors"
	"reflect"

	"google.golang.org/protobuf/proto"

	"buf.build/go/hyperpb/internal/structdec"
)

// Unmarshal parses wire-format data into msg.
//
// If msg is a [*Message], it uses hyperpb's zero-allocation dynamic parser.
// If msg is any other [proto.Message] (such as Go structs generated by
// protoc-gen-go), it uses hyperpb's high-performance struct decoder
// to decode directly into struct fields without reflection overhead.
func Unmarshal(data []byte, msg proto.Message, options ...UnmarshalOption) error {
	if msg == nil {
		return errors.New("hyperpb: message is nil")
	}
	if hm, ok := msg.(*Message); ok {
		return hm.Unmarshal(data, options...)
	}

	dec, err := structdec.Get(msg)
	if err != nil {
		return err
	}
	opts := toStructdecOptions(options...)
	return dec.DecodeMessage(msg, data, opts)
}

// StructDecoder is a precompiled decoder for standard protobuf messages of type T.
type StructDecoder[T proto.Message] struct {
	dec *structdec.Decoder
}

// CompileStruct compiles and returns a [StructDecoder] for message type T.
func CompileStruct[T proto.Message]() (*StructDecoder[T], error) {
	t := reflect.TypeFor[T]()
	dec, err := structdec.Compile(t)
	if err != nil {
		return nil, err
	}
	return &StructDecoder[T]{dec: dec}, nil
}

// Unmarshal parses wire-format data directly into msg.
func (d *StructDecoder[T]) Unmarshal(data []byte, msg T, options ...UnmarshalOption) error {
	opts := toStructdecOptions(options...)
	return d.dec.DecodeMessage(msg, data, opts)
}
