// Copyright 2025 Buf Technologies, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Package hyperjson is a high-performance protojson codec for hyperpb and
// standard protobuf messages.
//
// # Status
//
// This package implements the protojson wire format (JSON names, 64-bit integers
// as strings, well-known type shapes, etc.) for both [hyperpb.Message] values
// and standard [proto.Message] types generated by protoc-gen-go.
//
// [Marshal] serializes a message to JSON. For [hyperpb.Message], it walks the
// compiled tdp field tables directly, reading values through per-field getter
// thunks without allocations. For standard [proto.Message] types, it formats
// through the protoreflect surface.
//
// [Unmarshal] parses protojson into a message. For [hyperpb.Message], it writes
// directly into the hyperpb arena using a compiled per-type plan for maximum
// throughput and zero-allocation parsing, or falls back to descriptor-guided
// JSON-to-wire transcoding. For standard [proto.Message] types, it uses the
// fast transcoder to convert JSON directly into wire bytes and unmarshals into
// the target struct.
package hyperjson
